// flow-typed signature: 2df502adb42d9f5caddec27ba772feb3
// flow-typed version: <<STUB>>/@oneblink/apps_v0.1.0-beta.13/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@oneblink/apps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@oneblink/apps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@oneblink/apps/src/auth-service' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/auto-save-service' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/draft-service' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/form-service' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/job-service' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/notification-service' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/offline-service' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/payment-service' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/prefill-service' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/services/api/drafts' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/services/api/notifications' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/services/api/payment' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/services/api/prefill' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/services/api/submissions' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/services/cognito' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/services/draft-data-store' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/services/errors/oneBlinkAppsError' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/services/fetch' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/services/forms-key' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/services/job-prefill' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/services/pending-queue' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/services/recently-submitted-jobs' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/services/replace-custom-values' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/services/s3Submit' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/services/utils' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/submission-service' {
  declare module.exports: any;
}

declare module '@oneblink/apps/src/tenants' {
  declare module.exports: any;
}

// Filename aliases
declare module '@oneblink/apps/index' {
  declare module.exports: $Exports<'@oneblink/apps'>;
}
declare module '@oneblink/apps/index.js' {
  declare module.exports: $Exports<'@oneblink/apps'>;
}
declare module '@oneblink/apps/src/auth-service.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/auth-service'>;
}
declare module '@oneblink/apps/src/auto-save-service.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/auto-save-service'>;
}
declare module '@oneblink/apps/src/draft-service.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/draft-service'>;
}
declare module '@oneblink/apps/src/form-service.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/form-service'>;
}
declare module '@oneblink/apps/src/job-service.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/job-service'>;
}
declare module '@oneblink/apps/src/notification-service.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/notification-service'>;
}
declare module '@oneblink/apps/src/offline-service.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/offline-service'>;
}
declare module '@oneblink/apps/src/payment-service.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/payment-service'>;
}
declare module '@oneblink/apps/src/prefill-service.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/prefill-service'>;
}
declare module '@oneblink/apps/src/services/api/drafts.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/services/api/drafts'>;
}
declare module '@oneblink/apps/src/services/api/notifications.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/services/api/notifications'>;
}
declare module '@oneblink/apps/src/services/api/payment.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/services/api/payment'>;
}
declare module '@oneblink/apps/src/services/api/prefill.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/services/api/prefill'>;
}
declare module '@oneblink/apps/src/services/api/submissions.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/services/api/submissions'>;
}
declare module '@oneblink/apps/src/services/cognito.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/services/cognito'>;
}
declare module '@oneblink/apps/src/services/draft-data-store.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/services/draft-data-store'>;
}
declare module '@oneblink/apps/src/services/errors/oneBlinkAppsError.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/services/errors/oneBlinkAppsError'>;
}
declare module '@oneblink/apps/src/services/fetch.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/services/fetch'>;
}
declare module '@oneblink/apps/src/services/forms-key.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/services/forms-key'>;
}
declare module '@oneblink/apps/src/services/job-prefill.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/services/job-prefill'>;
}
declare module '@oneblink/apps/src/services/pending-queue.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/services/pending-queue'>;
}
declare module '@oneblink/apps/src/services/recently-submitted-jobs.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/services/recently-submitted-jobs'>;
}
declare module '@oneblink/apps/src/services/replace-custom-values.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/services/replace-custom-values'>;
}
declare module '@oneblink/apps/src/services/s3Submit.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/services/s3Submit'>;
}
declare module '@oneblink/apps/src/services/utils.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/services/utils'>;
}
declare module '@oneblink/apps/src/submission-service.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/submission-service'>;
}
declare module '@oneblink/apps/src/tenants.js' {
  declare module.exports: $Exports<'@oneblink/apps/src/tenants'>;
}
