// flow-typed signature: dc1167656a538a74d105cebb890c197f
// flow-typed version: <<STUB>>/@oneblink/flow-types_vgithub:oneblink/flow-types/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@oneblink/flow-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@oneblink/flow-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@oneblink/flow-types/flow-typed/forms' {
  declare module.exports: any;
}

declare module '@oneblink/flow-types/flow-typed/submission-events' {
  declare module.exports: any;
}

declare module '@oneblink/flow-types/flow-typed/submissions' {
  declare module.exports: any;
}

// Filename aliases
declare module '@oneblink/flow-types/flow-typed/forms.js' {
  declare module.exports: $Exports<'@oneblink/flow-types/flow-typed/forms'>;
}
declare module '@oneblink/flow-types/flow-typed/submission-events.js' {
  declare module.exports: $Exports<'@oneblink/flow-types/flow-typed/submission-events'>;
}
declare module '@oneblink/flow-types/flow-typed/submissions.js' {
  declare module.exports: $Exports<'@oneblink/flow-types/flow-typed/submissions'>;
}
