// flow-typed signature: 02a039351dabfcc03dcf09ef105505c5
// flow-typed version: <<STUB>>/@react-google-maps/api_v^1.9.12/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-google-maps/api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-google-maps/api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-google-maps/api/dist' {
  declare module.exports: any;
}

declare module '@react-google-maps/api/dist/reactgooglemapsapi.cjs.development' {
  declare module.exports: any;
}

declare module '@react-google-maps/api/dist/reactgooglemapsapi.cjs.production.min' {
  declare module.exports: any;
}

declare module '@react-google-maps/api/dist/reactgooglemapsapi.esm' {
  declare module.exports: any;
}

declare module '@react-google-maps/api/dist/reactgooglemapsapi.umd.development' {
  declare module.exports: any;
}

declare module '@react-google-maps/api/dist/reactgooglemapsapi.umd.production.min' {
  declare module.exports: any;
}

declare module '@react-google-maps/api/src/setup-tests' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-google-maps/api/dist/index' {
  declare module.exports: $Exports<'@react-google-maps/api/dist'>;
}
declare module '@react-google-maps/api/dist/index.js' {
  declare module.exports: $Exports<'@react-google-maps/api/dist'>;
}
declare module '@react-google-maps/api/dist/reactgooglemapsapi.cjs.development.js' {
  declare module.exports: $Exports<'@react-google-maps/api/dist/reactgooglemapsapi.cjs.development'>;
}
declare module '@react-google-maps/api/dist/reactgooglemapsapi.cjs.production.min.js' {
  declare module.exports: $Exports<'@react-google-maps/api/dist/reactgooglemapsapi.cjs.production.min'>;
}
declare module '@react-google-maps/api/dist/reactgooglemapsapi.esm.js' {
  declare module.exports: $Exports<'@react-google-maps/api/dist/reactgooglemapsapi.esm'>;
}
declare module '@react-google-maps/api/dist/reactgooglemapsapi.umd.development.js' {
  declare module.exports: $Exports<'@react-google-maps/api/dist/reactgooglemapsapi.umd.development'>;
}
declare module '@react-google-maps/api/dist/reactgooglemapsapi.umd.production.min.js' {
  declare module.exports: $Exports<'@react-google-maps/api/dist/reactgooglemapsapi.umd.production.min'>;
}
declare module '@react-google-maps/api/src/setup-tests.js' {
  declare module.exports: $Exports<'@react-google-maps/api/src/setup-tests'>;
}
