// flow-typed signature: 00aa64cdf19d250e6c739cb9fd525bcf
// flow-typed version: <<STUB>>/abortcontroller-polyfill_v^1.5.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'abortcontroller-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'abortcontroller-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'abortcontroller-polyfill/dist/abortcontroller-polyfill-only' {
  declare module.exports: any;
}

declare module 'abortcontroller-polyfill/dist/abortcontroller' {
  declare module.exports: any;
}

declare module 'abortcontroller-polyfill/dist/cjs-ponyfill' {
  declare module.exports: any;
}

declare module 'abortcontroller-polyfill/dist/polyfill-patch-fetch' {
  declare module.exports: any;
}

declare module 'abortcontroller-polyfill/dist/umd-polyfill' {
  declare module.exports: any;
}

declare module 'abortcontroller-polyfill/src/abortableFetch' {
  declare module.exports: any;
}

declare module 'abortcontroller-polyfill/src/abortcontroller-polyfill' {
  declare module.exports: any;
}

declare module 'abortcontroller-polyfill/src/abortcontroller' {
  declare module.exports: any;
}

declare module 'abortcontroller-polyfill/src/polyfill' {
  declare module.exports: any;
}

declare module 'abortcontroller-polyfill/src/ponyfill' {
  declare module.exports: any;
}

declare module 'abortcontroller-polyfill/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'abortcontroller-polyfill/dist/abortcontroller-polyfill-only.js' {
  declare module.exports: $Exports<'abortcontroller-polyfill/dist/abortcontroller-polyfill-only'>;
}
declare module 'abortcontroller-polyfill/dist/abortcontroller.js' {
  declare module.exports: $Exports<'abortcontroller-polyfill/dist/abortcontroller'>;
}
declare module 'abortcontroller-polyfill/dist/cjs-ponyfill.js' {
  declare module.exports: $Exports<'abortcontroller-polyfill/dist/cjs-ponyfill'>;
}
declare module 'abortcontroller-polyfill/dist/polyfill-patch-fetch.js' {
  declare module.exports: $Exports<'abortcontroller-polyfill/dist/polyfill-patch-fetch'>;
}
declare module 'abortcontroller-polyfill/dist/umd-polyfill.js' {
  declare module.exports: $Exports<'abortcontroller-polyfill/dist/umd-polyfill'>;
}
declare module 'abortcontroller-polyfill/src/abortableFetch.js' {
  declare module.exports: $Exports<'abortcontroller-polyfill/src/abortableFetch'>;
}
declare module 'abortcontroller-polyfill/src/abortcontroller-polyfill.js' {
  declare module.exports: $Exports<'abortcontroller-polyfill/src/abortcontroller-polyfill'>;
}
declare module 'abortcontroller-polyfill/src/abortcontroller.js' {
  declare module.exports: $Exports<'abortcontroller-polyfill/src/abortcontroller'>;
}
declare module 'abortcontroller-polyfill/src/polyfill.js' {
  declare module.exports: $Exports<'abortcontroller-polyfill/src/polyfill'>;
}
declare module 'abortcontroller-polyfill/src/ponyfill.js' {
  declare module.exports: $Exports<'abortcontroller-polyfill/src/ponyfill'>;
}
declare module 'abortcontroller-polyfill/src/utils.js' {
  declare module.exports: $Exports<'abortcontroller-polyfill/src/utils'>;
}
