// flow-typed signature: b51b848beee2ab35e90bb5a6b28f3d7b
// flow-typed version: <<STUB>>/abort-controller_v^3.0.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'abort-controller'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'abort-controller' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'abort-controller/browser' {
  declare module.exports: any;
}

declare module 'abort-controller/dist/abort-controller' {
  declare module.exports: any;
}

declare module 'abort-controller/dist/abort-controller.umd' {
  declare module.exports: any;
}

declare module 'abort-controller/polyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'abort-controller/browser.js' {
  declare module.exports: $Exports<'abort-controller/browser'>;
}
declare module 'abort-controller/dist/abort-controller.js' {
  declare module.exports: $Exports<'abort-controller/dist/abort-controller'>;
}
declare module 'abort-controller/dist/abort-controller.umd.js' {
  declare module.exports: $Exports<'abort-controller/dist/abort-controller.umd'>;
}
declare module 'abort-controller/polyfill.js' {
  declare module.exports: $Exports<'abort-controller/polyfill'>;
}
