// flow-typed signature: 14e5dc5fce78c2db753cde8e4384c664
// flow-typed version: <<STUB>>/blueimp-load-image_v^5.14.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blueimp-load-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blueimp-load-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blueimp-load-image/js' {
  declare module.exports: any;
}

declare module 'blueimp-load-image/js/load-image-exif-map' {
  declare module.exports: any;
}

declare module 'blueimp-load-image/js/load-image-exif' {
  declare module.exports: any;
}

declare module 'blueimp-load-image/js/load-image-fetch' {
  declare module.exports: any;
}

declare module 'blueimp-load-image/js/load-image-iptc-map' {
  declare module.exports: any;
}

declare module 'blueimp-load-image/js/load-image-iptc' {
  declare module.exports: any;
}

declare module 'blueimp-load-image/js/load-image-meta' {
  declare module.exports: any;
}

declare module 'blueimp-load-image/js/load-image-orientation' {
  declare module.exports: any;
}

declare module 'blueimp-load-image/js/load-image-scale' {
  declare module.exports: any;
}

declare module 'blueimp-load-image/js/load-image.all.min' {
  declare module.exports: any;
}

declare module 'blueimp-load-image/js/load-image' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blueimp-load-image/js/index' {
  declare module.exports: $Exports<'blueimp-load-image/js'>;
}
declare module 'blueimp-load-image/js/index.js' {
  declare module.exports: $Exports<'blueimp-load-image/js'>;
}
declare module 'blueimp-load-image/js/load-image-exif-map.js' {
  declare module.exports: $Exports<'blueimp-load-image/js/load-image-exif-map'>;
}
declare module 'blueimp-load-image/js/load-image-exif.js' {
  declare module.exports: $Exports<'blueimp-load-image/js/load-image-exif'>;
}
declare module 'blueimp-load-image/js/load-image-fetch.js' {
  declare module.exports: $Exports<'blueimp-load-image/js/load-image-fetch'>;
}
declare module 'blueimp-load-image/js/load-image-iptc-map.js' {
  declare module.exports: $Exports<'blueimp-load-image/js/load-image-iptc-map'>;
}
declare module 'blueimp-load-image/js/load-image-iptc.js' {
  declare module.exports: $Exports<'blueimp-load-image/js/load-image-iptc'>;
}
declare module 'blueimp-load-image/js/load-image-meta.js' {
  declare module.exports: $Exports<'blueimp-load-image/js/load-image-meta'>;
}
declare module 'blueimp-load-image/js/load-image-orientation.js' {
  declare module.exports: $Exports<'blueimp-load-image/js/load-image-orientation'>;
}
declare module 'blueimp-load-image/js/load-image-scale.js' {
  declare module.exports: $Exports<'blueimp-load-image/js/load-image-scale'>;
}
declare module 'blueimp-load-image/js/load-image.all.min.js' {
  declare module.exports: $Exports<'blueimp-load-image/js/load-image.all.min'>;
}
declare module 'blueimp-load-image/js/load-image.js' {
  declare module.exports: $Exports<'blueimp-load-image/js/load-image'>;
}
