// flow-typed signature: d3f7ffa13850ce02ba6edc1294319922
// flow-typed version: <<STUB>>/bulma_v^0.8.2/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma' {
  declare module.exports: any;
}
