// flow-typed signature: a854a7e89da54d5a50463daafa0c390d
// flow-typed version: <<STUB>>/bulma-badge_v3.0.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma-badge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma-badge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bulma-badge/src/demo/assets/js/bulma-calendar.min' {
  declare module.exports: any;
}

declare module 'bulma-badge/src/demo/assets/js/clipboard-1.7.1.min' {
  declare module.exports: any;
}

declare module 'bulma-badge/src/demo/assets/js/doc' {
  declare module.exports: any;
}

declare module 'bulma-badge/src/demo/assets/js/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bulma-badge/src/demo/assets/js/bulma-calendar.min.js' {
  declare module.exports: $Exports<'bulma-badge/src/demo/assets/js/bulma-calendar.min'>;
}
declare module 'bulma-badge/src/demo/assets/js/clipboard-1.7.1.min.js' {
  declare module.exports: $Exports<'bulma-badge/src/demo/assets/js/clipboard-1.7.1.min'>;
}
declare module 'bulma-badge/src/demo/assets/js/doc.js' {
  declare module.exports: $Exports<'bulma-badge/src/demo/assets/js/doc'>;
}
declare module 'bulma-badge/src/demo/assets/js/main.js' {
  declare module.exports: $Exports<'bulma-badge/src/demo/assets/js/main'>;
}
