// flow-typed signature: e69c933c4cc2f7d007aed2856f9f952e
// flow-typed version: <<STUB>>/bulma-steps_v^2.2.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma-steps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma-steps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bulma-steps/dist/js/bulma-steps' {
  declare module.exports: any;
}

declare module 'bulma-steps/dist/js/bulma-steps.min' {
  declare module.exports: any;
}

declare module 'bulma-steps/src/js/defaultOptions' {
  declare module.exports: any;
}

declare module 'bulma-steps/src/js/events' {
  declare module.exports: any;
}

declare module 'bulma-steps/src/js' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bulma-steps/dist/js/bulma-steps.js' {
  declare module.exports: $Exports<'bulma-steps/dist/js/bulma-steps'>;
}
declare module 'bulma-steps/dist/js/bulma-steps.min.js' {
  declare module.exports: $Exports<'bulma-steps/dist/js/bulma-steps.min'>;
}
declare module 'bulma-steps/src/js/defaultOptions.js' {
  declare module.exports: $Exports<'bulma-steps/src/js/defaultOptions'>;
}
declare module 'bulma-steps/src/js/events.js' {
  declare module.exports: $Exports<'bulma-steps/src/js/events'>;
}
declare module 'bulma-steps/src/js/index' {
  declare module.exports: $Exports<'bulma-steps/src/js'>;
}
declare module 'bulma-steps/src/js/index.js' {
  declare module.exports: $Exports<'bulma-steps/src/js'>;
}
