// flow-typed signature: 603f895b3ba6643aea5d01843f1dc4fd
// flow-typed version: <<STUB>>/bulma-slider_v^2.0.4/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma-slider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma-slider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bulma-slider/dist/js/bulma-slider' {
  declare module.exports: any;
}

declare module 'bulma-slider/dist/js/bulma-slider.min' {
  declare module.exports: any;
}

declare module 'bulma-slider/src/js/events' {
  declare module.exports: any;
}

declare module 'bulma-slider/src/js' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bulma-slider/dist/js/bulma-slider.js' {
  declare module.exports: $Exports<'bulma-slider/dist/js/bulma-slider'>;
}
declare module 'bulma-slider/dist/js/bulma-slider.min.js' {
  declare module.exports: $Exports<'bulma-slider/dist/js/bulma-slider.min'>;
}
declare module 'bulma-slider/src/js/events.js' {
  declare module.exports: $Exports<'bulma-slider/src/js/events'>;
}
declare module 'bulma-slider/src/js/index' {
  declare module.exports: $Exports<'bulma-slider/src/js'>;
}
declare module 'bulma-slider/src/js/index.js' {
  declare module.exports: $Exports<'bulma-slider/src/js'>;
}
