// flow-typed signature: 4bcb510f48431acb79e6bbc8486ce2c5
// flow-typed version: <<STUB>>/bulma-tooltip_v^3.0.2/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma-tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma-tooltip' {
  declare module.exports: any;
}
