// flow-typed signature: 20d682817b1d99fad7badf366dbfedae
// flow-typed version: <<STUB>>/bulma-toast_v^2.0.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma-toast'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma-toast' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bulma-toast/dist/bulma-toast.cjs' {
  declare module.exports: any;
}

declare module 'bulma-toast/dist/bulma-toast.esm' {
  declare module.exports: any;
}

declare module 'bulma-toast/dist/bulma-toast.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bulma-toast/dist/bulma-toast.cjs.js' {
  declare module.exports: $Exports<'bulma-toast/dist/bulma-toast.cjs'>;
}
declare module 'bulma-toast/dist/bulma-toast.esm.js' {
  declare module.exports: $Exports<'bulma-toast/dist/bulma-toast.esm'>;
}
declare module 'bulma-toast/dist/bulma-toast.min.js' {
  declare module.exports: $Exports<'bulma-toast/dist/bulma-toast.min'>;
}
