// flow-typed signature: 07f0eca5ac042a2567eb9fb8ac8b4cf2
// flow-typed version: <<STUB>>/cordova-plugin-whitelist_v^1.3.4/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova-plugin-whitelist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova-plugin-whitelist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cordova-plugin-whitelist/tests/scripts/remove-access' {
  declare module.exports: any;
}

declare module 'cordova-plugin-whitelist/tests/tests' {
  declare module.exports: any;
}

declare module 'cordova-plugin-whitelist/tests/www/whitelist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cordova-plugin-whitelist/tests/scripts/remove-access.js' {
  declare module.exports: $Exports<'cordova-plugin-whitelist/tests/scripts/remove-access'>;
}
declare module 'cordova-plugin-whitelist/tests/tests.js' {
  declare module.exports: $Exports<'cordova-plugin-whitelist/tests/tests'>;
}
declare module 'cordova-plugin-whitelist/tests/www/whitelist.js' {
  declare module.exports: $Exports<'cordova-plugin-whitelist/tests/www/whitelist'>;
}
