// flow-typed signature: 6be55c49c7a32b49cdcca106b38bb447
// flow-typed version: <<STUB>>/cordova-plugin-file-opener2_v^3.0.4/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova-plugin-file-opener2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova-plugin-file-opener2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cordova-plugin-file-opener2/src/browser/FileOpener2' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file-opener2/src/browser/FileSaver.min' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file-opener2/src/electron/FileOpener2' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file-opener2/src/windows/fileOpener2Proxy' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file-opener2/www/browser/isChrome' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file-opener2/www/plugins.FileOpener2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cordova-plugin-file-opener2/src/browser/FileOpener2.js' {
  declare module.exports: $Exports<'cordova-plugin-file-opener2/src/browser/FileOpener2'>;
}
declare module 'cordova-plugin-file-opener2/src/browser/FileSaver.min.js' {
  declare module.exports: $Exports<'cordova-plugin-file-opener2/src/browser/FileSaver.min'>;
}
declare module 'cordova-plugin-file-opener2/src/electron/FileOpener2.js' {
  declare module.exports: $Exports<'cordova-plugin-file-opener2/src/electron/FileOpener2'>;
}
declare module 'cordova-plugin-file-opener2/src/windows/fileOpener2Proxy.js' {
  declare module.exports: $Exports<'cordova-plugin-file-opener2/src/windows/fileOpener2Proxy'>;
}
declare module 'cordova-plugin-file-opener2/www/browser/isChrome.js' {
  declare module.exports: $Exports<'cordova-plugin-file-opener2/www/browser/isChrome'>;
}
declare module 'cordova-plugin-file-opener2/www/plugins.FileOpener2.js' {
  declare module.exports: $Exports<'cordova-plugin-file-opener2/www/plugins.FileOpener2'>;
}
