// flow-typed signature: f52fd14875baab2df96c10e833d3e35f
// flow-typed version: <<STUB>>/cordova-ios_v^6.1.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova-ios'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova-ios' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cordova-ios/bin/lib/create' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/lib/utils' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/project/www/js' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/Api' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/BridgingHeader' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/build' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/check_reqs' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/clean' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/listDevices' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/listEmulatorBuildTargets' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/listEmulatorImages' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/listStartedEmulators' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/plugman/pluginHandlers' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/Podfile' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/PodsJson' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/prepare' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/projectFile' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/run' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/versions' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/loggingHelper' {
  declare module.exports: any;
}

declare module 'cordova-ios/cordova-js-src/exec' {
  declare module.exports: any;
}

declare module 'cordova-ios/cordova-js-src/platform' {
  declare module.exports: any;
}

declare module 'cordova-ios/cordova-js-src/plugin/ios/console' {
  declare module.exports: any;
}

declare module 'cordova-ios/cordova-js-src/plugin/ios/launchscreen' {
  declare module.exports: any;
}

declare module 'cordova-ios/cordova-js-src/plugin/ios/logger' {
  declare module.exports: any;
}

declare module 'cordova-ios/cordova-js-src/plugin/ios/wkwebkit' {
  declare module.exports: any;
}

declare module 'cordova-ios/CordovaLib/cordova' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cordova-ios/bin/lib/create.js' {
  declare module.exports: $Exports<'cordova-ios/bin/lib/create'>;
}
declare module 'cordova-ios/bin/lib/utils.js' {
  declare module.exports: $Exports<'cordova-ios/bin/lib/utils'>;
}
declare module 'cordova-ios/bin/templates/project/www/js/index' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/project/www/js'>;
}
declare module 'cordova-ios/bin/templates/project/www/js/index.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/project/www/js'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/Api.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/Api'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/BridgingHeader.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/BridgingHeader'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/build.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/build'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/check_reqs.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/check_reqs'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/clean.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/clean'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/listDevices.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/listDevices'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/listEmulatorBuildTargets.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/listEmulatorBuildTargets'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/listEmulatorImages.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/listEmulatorImages'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/listStartedEmulators.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/listStartedEmulators'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/plugman/pluginHandlers.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/plugman/pluginHandlers'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/Podfile.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/Podfile'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/PodsJson.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/PodsJson'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/prepare.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/prepare'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/projectFile.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/projectFile'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/run.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/run'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/versions.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/versions'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/loggingHelper.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/loggingHelper'>;
}
declare module 'cordova-ios/cordova-js-src/exec.js' {
  declare module.exports: $Exports<'cordova-ios/cordova-js-src/exec'>;
}
declare module 'cordova-ios/cordova-js-src/platform.js' {
  declare module.exports: $Exports<'cordova-ios/cordova-js-src/platform'>;
}
declare module 'cordova-ios/cordova-js-src/plugin/ios/console.js' {
  declare module.exports: $Exports<'cordova-ios/cordova-js-src/plugin/ios/console'>;
}
declare module 'cordova-ios/cordova-js-src/plugin/ios/launchscreen.js' {
  declare module.exports: $Exports<'cordova-ios/cordova-js-src/plugin/ios/launchscreen'>;
}
declare module 'cordova-ios/cordova-js-src/plugin/ios/logger.js' {
  declare module.exports: $Exports<'cordova-ios/cordova-js-src/plugin/ios/logger'>;
}
declare module 'cordova-ios/cordova-js-src/plugin/ios/wkwebkit.js' {
  declare module.exports: $Exports<'cordova-ios/cordova-js-src/plugin/ios/wkwebkit'>;
}
declare module 'cordova-ios/CordovaLib/cordova.js' {
  declare module.exports: $Exports<'cordova-ios/CordovaLib/cordova'>;
}
