// flow-typed signature: b4576865b9df7aa33a819910708e30cc
// flow-typed version: <<STUB>>/cordova-plugin-camera_v^4.1.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova-plugin-camera'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova-plugin-camera' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cordova-plugin-camera/src/browser/CameraProxy' {
  declare module.exports: any;
}

declare module 'cordova-plugin-camera/src/windows/CameraProxy' {
  declare module.exports: any;
}

declare module 'cordova-plugin-camera/tests/tests' {
  declare module.exports: any;
}

declare module 'cordova-plugin-camera/www/Camera' {
  declare module.exports: any;
}

declare module 'cordova-plugin-camera/www/CameraConstants' {
  declare module.exports: any;
}

declare module 'cordova-plugin-camera/www/CameraPopoverHandle' {
  declare module.exports: any;
}

declare module 'cordova-plugin-camera/www/CameraPopoverOptions' {
  declare module.exports: any;
}

declare module 'cordova-plugin-camera/www/ios/CameraPopoverHandle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cordova-plugin-camera/src/browser/CameraProxy.js' {
  declare module.exports: $Exports<'cordova-plugin-camera/src/browser/CameraProxy'>;
}
declare module 'cordova-plugin-camera/src/windows/CameraProxy.js' {
  declare module.exports: $Exports<'cordova-plugin-camera/src/windows/CameraProxy'>;
}
declare module 'cordova-plugin-camera/tests/tests.js' {
  declare module.exports: $Exports<'cordova-plugin-camera/tests/tests'>;
}
declare module 'cordova-plugin-camera/www/Camera.js' {
  declare module.exports: $Exports<'cordova-plugin-camera/www/Camera'>;
}
declare module 'cordova-plugin-camera/www/CameraConstants.js' {
  declare module.exports: $Exports<'cordova-plugin-camera/www/CameraConstants'>;
}
declare module 'cordova-plugin-camera/www/CameraPopoverHandle.js' {
  declare module.exports: $Exports<'cordova-plugin-camera/www/CameraPopoverHandle'>;
}
declare module 'cordova-plugin-camera/www/CameraPopoverOptions.js' {
  declare module.exports: $Exports<'cordova-plugin-camera/www/CameraPopoverOptions'>;
}
declare module 'cordova-plugin-camera/www/ios/CameraPopoverHandle.js' {
  declare module.exports: $Exports<'cordova-plugin-camera/www/ios/CameraPopoverHandle'>;
}
