// flow-typed signature: 01998912ab630300198ac51892f4a627
// flow-typed version: <<STUB>>/cordova-plugin-splashscreen_v^6.0.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova-plugin-splashscreen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova-plugin-splashscreen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cordova-plugin-splashscreen/src/browser/SplashScreenProxy' {
  declare module.exports: any;
}

declare module 'cordova-plugin-splashscreen/src/windows/SplashScreenProxy' {
  declare module.exports: any;
}

declare module 'cordova-plugin-splashscreen/www/splashscreen' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cordova-plugin-splashscreen/src/browser/SplashScreenProxy.js' {
  declare module.exports: $Exports<'cordova-plugin-splashscreen/src/browser/SplashScreenProxy'>;
}
declare module 'cordova-plugin-splashscreen/src/windows/SplashScreenProxy.js' {
  declare module.exports: $Exports<'cordova-plugin-splashscreen/src/windows/SplashScreenProxy'>;
}
declare module 'cordova-plugin-splashscreen/www/splashscreen.js' {
  declare module.exports: $Exports<'cordova-plugin-splashscreen/www/splashscreen'>;
}
