// flow-typed signature: 131507e0c69c539e9261a1b6c8c57264
// flow-typed version: <<STUB>>/cordova-plugin-network-information_v^2.0.2/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova-plugin-network-information'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova-plugin-network-information' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cordova-plugin-network-information/src/browser/network' {
  declare module.exports: any;
}

declare module 'cordova-plugin-network-information/src/windows/NetworkInfoProxy' {
  declare module.exports: any;
}

declare module 'cordova-plugin-network-information/tests/tests' {
  declare module.exports: any;
}

declare module 'cordova-plugin-network-information/www/Connection' {
  declare module.exports: any;
}

declare module 'cordova-plugin-network-information/www/network' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cordova-plugin-network-information/src/browser/network.js' {
  declare module.exports: $Exports<'cordova-plugin-network-information/src/browser/network'>;
}
declare module 'cordova-plugin-network-information/src/windows/NetworkInfoProxy.js' {
  declare module.exports: $Exports<'cordova-plugin-network-information/src/windows/NetworkInfoProxy'>;
}
declare module 'cordova-plugin-network-information/tests/tests.js' {
  declare module.exports: $Exports<'cordova-plugin-network-information/tests/tests'>;
}
declare module 'cordova-plugin-network-information/www/Connection.js' {
  declare module.exports: $Exports<'cordova-plugin-network-information/www/Connection'>;
}
declare module 'cordova-plugin-network-information/www/network.js' {
  declare module.exports: $Exports<'cordova-plugin-network-information/www/network'>;
}
