// flow-typed signature: 5587218f2bd0661a209cf4a3f75e9430
// flow-typed version: <<STUB>>/cordova-plugin-ionic-webview_v^5.0.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova-plugin-ionic-webview'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova-plugin-ionic-webview' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cordova-plugin-ionic-webview/src/ios/wk-plugin' {
  declare module.exports: any;
}

declare module 'cordova-plugin-ionic-webview/src/www/ios/ios-wkwebview-exec' {
  declare module.exports: any;
}

declare module 'cordova-plugin-ionic-webview/src/www/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cordova-plugin-ionic-webview/src/ios/wk-plugin.js' {
  declare module.exports: $Exports<'cordova-plugin-ionic-webview/src/ios/wk-plugin'>;
}
declare module 'cordova-plugin-ionic-webview/src/www/ios/ios-wkwebview-exec.js' {
  declare module.exports: $Exports<'cordova-plugin-ionic-webview/src/www/ios/ios-wkwebview-exec'>;
}
declare module 'cordova-plugin-ionic-webview/src/www/util.js' {
  declare module.exports: $Exports<'cordova-plugin-ionic-webview/src/www/util'>;
}
