// flow-typed signature: cb5c597558a3d635ccbcf9285d72f895
// flow-typed version: <<STUB>>/cordova-plugin-exit_v^1.0.3/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova-plugin-exit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova-plugin-exit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cordova-plugin-exit/www/exit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cordova-plugin-exit/www/exit.js' {
  declare module.exports: $Exports<'cordova-plugin-exit/www/exit'>;
}
