// flow-typed signature: e6d312ce3a8b79f5349f1888e52be325
// flow-typed version: <<STUB>>/cordova-android_v^9.0.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova-android'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova-android' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cordova-android/bin/clean_test' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/lib/create' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/lib/utils' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/Api' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/Adb' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/android_sdk' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/AndroidManifest' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/AndroidProject' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/build' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/builders/builders' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/builders/ProjectBuilder' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/check_reqs' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/config/GradlePropertiesParser' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/device' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/emulator' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/log' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/PackageType' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/pluginHandlers' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/prepare' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/retry' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/run' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/utils' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/loggingHelper' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/project/assets/www/cordova' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/project/assets/www/js' {
  declare module.exports: any;
}

declare module 'cordova-android/cordova-js-src/android/nativeapiprovider' {
  declare module.exports: any;
}

declare module 'cordova-android/cordova-js-src/android/promptbasednativeapi' {
  declare module.exports: any;
}

declare module 'cordova-android/cordova-js-src/exec' {
  declare module.exports: any;
}

declare module 'cordova-android/cordova-js-src/platform' {
  declare module.exports: any;
}

declare module 'cordova-android/cordova-js-src/plugin/android/app' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cordova-android/bin/clean_test.js' {
  declare module.exports: $Exports<'cordova-android/bin/clean_test'>;
}
declare module 'cordova-android/bin/lib/create.js' {
  declare module.exports: $Exports<'cordova-android/bin/lib/create'>;
}
declare module 'cordova-android/bin/lib/utils.js' {
  declare module.exports: $Exports<'cordova-android/bin/lib/utils'>;
}
declare module 'cordova-android/bin/templates/cordova/Api.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/Api'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/Adb.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/Adb'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/android_sdk.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/android_sdk'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/AndroidManifest.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/AndroidManifest'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/AndroidProject.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/AndroidProject'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/build.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/build'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/builders/builders.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/builders/builders'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/builders/ProjectBuilder.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/builders/ProjectBuilder'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/check_reqs.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/check_reqs'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/config/GradlePropertiesParser.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/config/GradlePropertiesParser'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/device.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/device'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/emulator.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/emulator'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/log.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/log'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/PackageType.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/PackageType'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/pluginHandlers.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/pluginHandlers'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/prepare.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/prepare'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/retry.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/retry'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/run.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/run'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/utils.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/utils'>;
}
declare module 'cordova-android/bin/templates/cordova/loggingHelper.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/loggingHelper'>;
}
declare module 'cordova-android/bin/templates/project/assets/www/cordova.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/project/assets/www/cordova'>;
}
declare module 'cordova-android/bin/templates/project/assets/www/js/index' {
  declare module.exports: $Exports<'cordova-android/bin/templates/project/assets/www/js'>;
}
declare module 'cordova-android/bin/templates/project/assets/www/js/index.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/project/assets/www/js'>;
}
declare module 'cordova-android/cordova-js-src/android/nativeapiprovider.js' {
  declare module.exports: $Exports<'cordova-android/cordova-js-src/android/nativeapiprovider'>;
}
declare module 'cordova-android/cordova-js-src/android/promptbasednativeapi.js' {
  declare module.exports: $Exports<'cordova-android/cordova-js-src/android/promptbasednativeapi'>;
}
declare module 'cordova-android/cordova-js-src/exec.js' {
  declare module.exports: $Exports<'cordova-android/cordova-js-src/exec'>;
}
declare module 'cordova-android/cordova-js-src/platform.js' {
  declare module.exports: $Exports<'cordova-android/cordova-js-src/platform'>;
}
declare module 'cordova-android/cordova-js-src/plugin/android/app.js' {
  declare module.exports: $Exports<'cordova-android/cordova-js-src/plugin/android/app'>;
}
