// flow-typed signature: 350ef22a601919851161dac2032837dc
// flow-typed version: <<STUB>>/element-remove_v^1.0.4/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'element-remove'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'element-remove' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'element-remove/index' {
  declare module.exports: $Exports<'element-remove'>;
}
declare module 'element-remove/index.js' {
  declare module.exports: $Exports<'element-remove'>;
}
