// flow-typed signature: 638c8d8530e0b93db0927494cd36afc6
// flow-typed version: <<STUB>>/escape-string-regexp_v^4.0.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'escape-string-regexp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'escape-string-regexp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'escape-string-regexp/index' {
  declare module.exports: $Exports<'escape-string-regexp'>;
}
declare module 'escape-string-regexp/index.js' {
  declare module.exports: $Exports<'escape-string-regexp'>;
}
