// flow-typed signature: a6ae55ff7fefe74f35ac2278ac4acb88
// flow-typed version: <<STUB>>/flatpickr_v4.6.3/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flatpickr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flatpickr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flatpickr/dist/flatpickr' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/flatpickr.min' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/ar' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/at' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/az' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/be' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/bg' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/bn' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/bs' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/cat' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/cs' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/cy' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/da' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/de' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/default' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/eo' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/es' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/et' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/fa' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/fi' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/fo' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/fr' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/ga' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/gr' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/he' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/hi' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/hr' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/hu' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/id' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/is' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/it' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/ja' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/ka' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/km' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/ko' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/kz' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/lt' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/lv' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/mk' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/mn' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/ms' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/my' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/nl' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/no' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/pa' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/pl' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/pt' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/ro' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/ru' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/si' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/sk' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/sl' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/sq' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/sr-cyr' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/sr' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/sv' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/th' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/tr' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/uk' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/vn' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/zh-tw' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/l10n/zh' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/plugins/confirmDate/confirmDate' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/plugins/labelPlugin/labelPlugin' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/plugins/minMaxTimePlugin' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/plugins/monthSelect' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/plugins/rangePlugin' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/plugins/scrollPlugin' {
  declare module.exports: any;
}

declare module 'flatpickr/dist/plugins/weekSelect/weekSelect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flatpickr/dist/flatpickr.js' {
  declare module.exports: $Exports<'flatpickr/dist/flatpickr'>;
}
declare module 'flatpickr/dist/flatpickr.min.js' {
  declare module.exports: $Exports<'flatpickr/dist/flatpickr.min'>;
}
declare module 'flatpickr/dist/l10n/ar.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/ar'>;
}
declare module 'flatpickr/dist/l10n/at.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/at'>;
}
declare module 'flatpickr/dist/l10n/az.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/az'>;
}
declare module 'flatpickr/dist/l10n/be.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/be'>;
}
declare module 'flatpickr/dist/l10n/bg.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/bg'>;
}
declare module 'flatpickr/dist/l10n/bn.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/bn'>;
}
declare module 'flatpickr/dist/l10n/bs.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/bs'>;
}
declare module 'flatpickr/dist/l10n/cat.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/cat'>;
}
declare module 'flatpickr/dist/l10n/cs.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/cs'>;
}
declare module 'flatpickr/dist/l10n/cy.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/cy'>;
}
declare module 'flatpickr/dist/l10n/da.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/da'>;
}
declare module 'flatpickr/dist/l10n/de.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/de'>;
}
declare module 'flatpickr/dist/l10n/default.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/default'>;
}
declare module 'flatpickr/dist/l10n/eo.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/eo'>;
}
declare module 'flatpickr/dist/l10n/es.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/es'>;
}
declare module 'flatpickr/dist/l10n/et.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/et'>;
}
declare module 'flatpickr/dist/l10n/fa.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/fa'>;
}
declare module 'flatpickr/dist/l10n/fi.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/fi'>;
}
declare module 'flatpickr/dist/l10n/fo.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/fo'>;
}
declare module 'flatpickr/dist/l10n/fr.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/fr'>;
}
declare module 'flatpickr/dist/l10n/ga.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/ga'>;
}
declare module 'flatpickr/dist/l10n/gr.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/gr'>;
}
declare module 'flatpickr/dist/l10n/he.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/he'>;
}
declare module 'flatpickr/dist/l10n/hi.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/hi'>;
}
declare module 'flatpickr/dist/l10n/hr.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/hr'>;
}
declare module 'flatpickr/dist/l10n/hu.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/hu'>;
}
declare module 'flatpickr/dist/l10n/id.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/id'>;
}
declare module 'flatpickr/dist/l10n/index' {
  declare module.exports: $Exports<'flatpickr/dist/l10n'>;
}
declare module 'flatpickr/dist/l10n/index.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n'>;
}
declare module 'flatpickr/dist/l10n/is.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/is'>;
}
declare module 'flatpickr/dist/l10n/it.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/it'>;
}
declare module 'flatpickr/dist/l10n/ja.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/ja'>;
}
declare module 'flatpickr/dist/l10n/ka.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/ka'>;
}
declare module 'flatpickr/dist/l10n/km.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/km'>;
}
declare module 'flatpickr/dist/l10n/ko.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/ko'>;
}
declare module 'flatpickr/dist/l10n/kz.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/kz'>;
}
declare module 'flatpickr/dist/l10n/lt.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/lt'>;
}
declare module 'flatpickr/dist/l10n/lv.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/lv'>;
}
declare module 'flatpickr/dist/l10n/mk.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/mk'>;
}
declare module 'flatpickr/dist/l10n/mn.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/mn'>;
}
declare module 'flatpickr/dist/l10n/ms.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/ms'>;
}
declare module 'flatpickr/dist/l10n/my.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/my'>;
}
declare module 'flatpickr/dist/l10n/nl.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/nl'>;
}
declare module 'flatpickr/dist/l10n/no.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/no'>;
}
declare module 'flatpickr/dist/l10n/pa.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/pa'>;
}
declare module 'flatpickr/dist/l10n/pl.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/pl'>;
}
declare module 'flatpickr/dist/l10n/pt.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/pt'>;
}
declare module 'flatpickr/dist/l10n/ro.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/ro'>;
}
declare module 'flatpickr/dist/l10n/ru.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/ru'>;
}
declare module 'flatpickr/dist/l10n/si.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/si'>;
}
declare module 'flatpickr/dist/l10n/sk.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/sk'>;
}
declare module 'flatpickr/dist/l10n/sl.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/sl'>;
}
declare module 'flatpickr/dist/l10n/sq.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/sq'>;
}
declare module 'flatpickr/dist/l10n/sr-cyr.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/sr-cyr'>;
}
declare module 'flatpickr/dist/l10n/sr.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/sr'>;
}
declare module 'flatpickr/dist/l10n/sv.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/sv'>;
}
declare module 'flatpickr/dist/l10n/th.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/th'>;
}
declare module 'flatpickr/dist/l10n/tr.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/tr'>;
}
declare module 'flatpickr/dist/l10n/uk.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/uk'>;
}
declare module 'flatpickr/dist/l10n/vn.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/vn'>;
}
declare module 'flatpickr/dist/l10n/zh-tw.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/zh-tw'>;
}
declare module 'flatpickr/dist/l10n/zh.js' {
  declare module.exports: $Exports<'flatpickr/dist/l10n/zh'>;
}
declare module 'flatpickr/dist/plugins/confirmDate/confirmDate.js' {
  declare module.exports: $Exports<'flatpickr/dist/plugins/confirmDate/confirmDate'>;
}
declare module 'flatpickr/dist/plugins/labelPlugin/labelPlugin.js' {
  declare module.exports: $Exports<'flatpickr/dist/plugins/labelPlugin/labelPlugin'>;
}
declare module 'flatpickr/dist/plugins/minMaxTimePlugin.js' {
  declare module.exports: $Exports<'flatpickr/dist/plugins/minMaxTimePlugin'>;
}
declare module 'flatpickr/dist/plugins/monthSelect/index' {
  declare module.exports: $Exports<'flatpickr/dist/plugins/monthSelect'>;
}
declare module 'flatpickr/dist/plugins/monthSelect/index.js' {
  declare module.exports: $Exports<'flatpickr/dist/plugins/monthSelect'>;
}
declare module 'flatpickr/dist/plugins/rangePlugin.js' {
  declare module.exports: $Exports<'flatpickr/dist/plugins/rangePlugin'>;
}
declare module 'flatpickr/dist/plugins/scrollPlugin.js' {
  declare module.exports: $Exports<'flatpickr/dist/plugins/scrollPlugin'>;
}
declare module 'flatpickr/dist/plugins/weekSelect/weekSelect.js' {
  declare module.exports: $Exports<'flatpickr/dist/plugins/weekSelect/weekSelect'>;
}
