// flow-typed signature: c6236fb7ae2b572d47c512f6562ce2f8
// flow-typed version: <<STUB>>/getusermedia_v^2.0.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'getusermedia'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'getusermedia' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'getusermedia/build' {
  declare module.exports: any;
}

declare module 'getusermedia/getusermedia.bundle' {
  declare module.exports: any;
}

declare module 'getusermedia/getusermedia' {
  declare module.exports: any;
}

declare module 'getusermedia/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'getusermedia/build.js' {
  declare module.exports: $Exports<'getusermedia/build'>;
}
declare module 'getusermedia/getusermedia.bundle.js' {
  declare module.exports: $Exports<'getusermedia/getusermedia.bundle'>;
}
declare module 'getusermedia/getusermedia.js' {
  declare module.exports: $Exports<'getusermedia/getusermedia'>;
}
declare module 'getusermedia/test/test.js' {
  declare module.exports: $Exports<'getusermedia/test/test'>;
}
