// flow-typed signature: 1e0f32d1e7638a5d43a0c80e4cef9d51
// flow-typed version: <<STUB>>/jsqr_v^1.3.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsqr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsqr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsqr/dist/jsQR' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsqr/dist/jsQR.js' {
  declare module.exports: $Exports<'jsqr/dist/jsQR'>;
}
