// flow-typed signature: 30e84a56aab52dde5138177aedfe78fa
// flow-typed version: <<STUB>>/local-storage_v^2.0.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'local-storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'local-storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'local-storage/dist/local-storage' {
  declare module.exports: any;
}

declare module 'local-storage/local-storage' {
  declare module.exports: any;
}

declare module 'local-storage/parse' {
  declare module.exports: any;
}

declare module 'local-storage/stub' {
  declare module.exports: any;
}

declare module 'local-storage/tracking' {
  declare module.exports: any;
}

// Filename aliases
declare module 'local-storage/dist/local-storage.js' {
  declare module.exports: $Exports<'local-storage/dist/local-storage'>;
}
declare module 'local-storage/local-storage.js' {
  declare module.exports: $Exports<'local-storage/local-storage'>;
}
declare module 'local-storage/parse.js' {
  declare module.exports: $Exports<'local-storage/parse'>;
}
declare module 'local-storage/stub.js' {
  declare module.exports: $Exports<'local-storage/stub'>;
}
declare module 'local-storage/tracking.js' {
  declare module.exports: $Exports<'local-storage/tracking'>;
}
