// flow-typed signature: 04f1ae51f6e6fe098079072d508e33a2
// flow-typed version: <<STUB>>/morph-expressions_v^1.1.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'morph-expressions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'morph-expressions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'morph-expressions/dist/morph-expression' {
  declare module.exports: any;
}

declare module 'morph-expressions/dist/morph-expression.min' {
  declare module.exports: any;
}

declare module 'morph-expressions/es/__tests__/parser.test' {
  declare module.exports: any;
}

declare module 'morph-expressions/es/abstract-syntax-tree' {
  declare module.exports: any;
}

declare module 'morph-expressions/es' {
  declare module.exports: any;
}

declare module 'morph-expressions/es/parser' {
  declare module.exports: any;
}

declare module 'morph-expressions/es/tokenizer/keywords-tree' {
  declare module.exports: any;
}

declare module 'morph-expressions/es/tokenizer/lexeme-tree' {
  declare module.exports: any;
}

declare module 'morph-expressions/es/tokenizer/tokenizer' {
  declare module.exports: any;
}

declare module 'morph-expressions/es/tokenizer/types' {
  declare module.exports: any;
}

declare module 'morph-expressions/lib/__tests__/parser.test' {
  declare module.exports: any;
}

declare module 'morph-expressions/lib/abstract-syntax-tree' {
  declare module.exports: any;
}

declare module 'morph-expressions/lib' {
  declare module.exports: any;
}

declare module 'morph-expressions/lib/parser' {
  declare module.exports: any;
}

declare module 'morph-expressions/lib/tokenizer/keywords-tree' {
  declare module.exports: any;
}

declare module 'morph-expressions/lib/tokenizer/lexeme-tree' {
  declare module.exports: any;
}

declare module 'morph-expressions/lib/tokenizer/tokenizer' {
  declare module.exports: any;
}

declare module 'morph-expressions/lib/tokenizer/types' {
  declare module.exports: any;
}

declare module 'morph-expressions/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'morph-expressions/dist/morph-expression.js' {
  declare module.exports: $Exports<'morph-expressions/dist/morph-expression'>;
}
declare module 'morph-expressions/dist/morph-expression.min.js' {
  declare module.exports: $Exports<'morph-expressions/dist/morph-expression.min'>;
}
declare module 'morph-expressions/es/__tests__/parser.test.js' {
  declare module.exports: $Exports<'morph-expressions/es/__tests__/parser.test'>;
}
declare module 'morph-expressions/es/abstract-syntax-tree.js' {
  declare module.exports: $Exports<'morph-expressions/es/abstract-syntax-tree'>;
}
declare module 'morph-expressions/es/index' {
  declare module.exports: $Exports<'morph-expressions/es'>;
}
declare module 'morph-expressions/es/index.js' {
  declare module.exports: $Exports<'morph-expressions/es'>;
}
declare module 'morph-expressions/es/parser.js' {
  declare module.exports: $Exports<'morph-expressions/es/parser'>;
}
declare module 'morph-expressions/es/tokenizer/keywords-tree.js' {
  declare module.exports: $Exports<'morph-expressions/es/tokenizer/keywords-tree'>;
}
declare module 'morph-expressions/es/tokenizer/lexeme-tree.js' {
  declare module.exports: $Exports<'morph-expressions/es/tokenizer/lexeme-tree'>;
}
declare module 'morph-expressions/es/tokenizer/tokenizer.js' {
  declare module.exports: $Exports<'morph-expressions/es/tokenizer/tokenizer'>;
}
declare module 'morph-expressions/es/tokenizer/types.js' {
  declare module.exports: $Exports<'morph-expressions/es/tokenizer/types'>;
}
declare module 'morph-expressions/lib/__tests__/parser.test.js' {
  declare module.exports: $Exports<'morph-expressions/lib/__tests__/parser.test'>;
}
declare module 'morph-expressions/lib/abstract-syntax-tree.js' {
  declare module.exports: $Exports<'morph-expressions/lib/abstract-syntax-tree'>;
}
declare module 'morph-expressions/lib/index' {
  declare module.exports: $Exports<'morph-expressions/lib'>;
}
declare module 'morph-expressions/lib/index.js' {
  declare module.exports: $Exports<'morph-expressions/lib'>;
}
declare module 'morph-expressions/lib/parser.js' {
  declare module.exports: $Exports<'morph-expressions/lib/parser'>;
}
declare module 'morph-expressions/lib/tokenizer/keywords-tree.js' {
  declare module.exports: $Exports<'morph-expressions/lib/tokenizer/keywords-tree'>;
}
declare module 'morph-expressions/lib/tokenizer/lexeme-tree.js' {
  declare module.exports: $Exports<'morph-expressions/lib/tokenizer/lexeme-tree'>;
}
declare module 'morph-expressions/lib/tokenizer/tokenizer.js' {
  declare module.exports: $Exports<'morph-expressions/lib/tokenizer/tokenizer'>;
}
declare module 'morph-expressions/lib/tokenizer/types.js' {
  declare module.exports: $Exports<'morph-expressions/lib/tokenizer/types'>;
}
declare module 'morph-expressions/webpack.config.js' {
  declare module.exports: $Exports<'morph-expressions/webpack.config'>;
}
