// flow-typed signature: b86c28cc11deccba8dc67fbc933c9f17
// flow-typed version: <<STUB>>/phonegap-plugin-barcodescanner_v^8.1.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'phonegap-plugin-barcodescanner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'phonegap-plugin-barcodescanner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'phonegap-plugin-barcodescanner/hooks/windows/check-arch' {
  declare module.exports: any;
}

declare module 'phonegap-plugin-barcodescanner/spec/helper/cordova' {
  declare module.exports: any;
}

declare module 'phonegap-plugin-barcodescanner/spec/index.spec' {
  declare module.exports: any;
}

declare module 'phonegap-plugin-barcodescanner/src/browser/BarcodeScannerProxy' {
  declare module.exports: any;
}

declare module 'phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy' {
  declare module.exports: any;
}

declare module 'phonegap-plugin-barcodescanner/www/barcodescanner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'phonegap-plugin-barcodescanner/hooks/windows/check-arch.js' {
  declare module.exports: $Exports<'phonegap-plugin-barcodescanner/hooks/windows/check-arch'>;
}
declare module 'phonegap-plugin-barcodescanner/spec/helper/cordova.js' {
  declare module.exports: $Exports<'phonegap-plugin-barcodescanner/spec/helper/cordova'>;
}
declare module 'phonegap-plugin-barcodescanner/spec/index.spec.js' {
  declare module.exports: $Exports<'phonegap-plugin-barcodescanner/spec/index.spec'>;
}
declare module 'phonegap-plugin-barcodescanner/src/browser/BarcodeScannerProxy.js' {
  declare module.exports: $Exports<'phonegap-plugin-barcodescanner/src/browser/BarcodeScannerProxy'>;
}
declare module 'phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js' {
  declare module.exports: $Exports<'phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy'>;
}
declare module 'phonegap-plugin-barcodescanner/www/barcodescanner.js' {
  declare module.exports: $Exports<'phonegap-plugin-barcodescanner/www/barcodescanner'>;
}
