// flow-typed signature: 004a374888f2477316d1776c3b22922e
// flow-typed version: <<STUB>>/quagga_v^0.12.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'quagga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'quagga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'quagga/dist/quagga' {
  declare module.exports: any;
}

declare module 'quagga/dist/quagga.min' {
  declare module.exports: any;
}

declare module 'quagga/env/development' {
  declare module.exports: any;
}

declare module 'quagga/env/node' {
  declare module.exports: any;
}

declare module 'quagga/env/production' {
  declare module.exports: any;
}

declare module 'quagga/Gruntfile' {
  declare module.exports: any;
}

declare module 'quagga/karma-integration.conf' {
  declare module.exports: any;
}

declare module 'quagga/karma.conf' {
  declare module.exports: any;
}

declare module 'quagga/lib/frame_grabber' {
  declare module.exports: any;
}

declare module 'quagga/lib/input_stream' {
  declare module.exports: any;
}

declare module 'quagga/lib/quagga' {
  declare module.exports: any;
}

declare module 'quagga/plugins/umd' {
  declare module.exports: any;
}

declare module 'quagga/src/analytics/result_collector' {
  declare module.exports: any;
}

declare module 'quagga/src/common/array_helper' {
  declare module.exports: any;
}

declare module 'quagga/src/common/cluster' {
  declare module.exports: any;
}

declare module 'quagga/src/common/cv_utils' {
  declare module.exports: any;
}

declare module 'quagga/src/common/events' {
  declare module.exports: any;
}

declare module 'quagga/src/common/image_debug' {
  declare module.exports: any;
}

declare module 'quagga/src/common/image_wrapper' {
  declare module.exports: any;
}

declare module 'quagga/src/common/mediaDevices' {
  declare module.exports: any;
}

declare module 'quagga/src/common/subImage' {
  declare module.exports: any;
}

declare module 'quagga/src/common/typedefs' {
  declare module.exports: any;
}

declare module 'quagga/src/config/config.dev' {
  declare module.exports: any;
}

declare module 'quagga/src/config/config' {
  declare module.exports: any;
}

declare module 'quagga/src/config/config.node' {
  declare module.exports: any;
}

declare module 'quagga/src/config/config.prod' {
  declare module.exports: any;
}

declare module 'quagga/src/decoder/barcode_decoder' {
  declare module.exports: any;
}

declare module 'quagga/src/decoder/bresenham' {
  declare module.exports: any;
}

declare module 'quagga/src/input/camera_access' {
  declare module.exports: any;
}

declare module 'quagga/src/input/exif_helper' {
  declare module.exports: any;
}

declare module 'quagga/src/input/frame_grabber' {
  declare module.exports: any;
}

declare module 'quagga/src/input/image_loader' {
  declare module.exports: any;
}

declare module 'quagga/src/input/input_stream' {
  declare module.exports: any;
}

declare module 'quagga/src/locator/barcode_locator' {
  declare module.exports: any;
}

declare module 'quagga/src/locator/rasterizer' {
  declare module.exports: any;
}

declare module 'quagga/src/locator/skeletonizer' {
  declare module.exports: any;
}

declare module 'quagga/src/locator/tracer' {
  declare module.exports: any;
}

declare module 'quagga/src/quagga' {
  declare module.exports: any;
}

declare module 'quagga/src/reader/2of5_reader' {
  declare module.exports: any;
}

declare module 'quagga/src/reader/barcode_reader' {
  declare module.exports: any;
}

declare module 'quagga/src/reader/codabar_reader' {
  declare module.exports: any;
}

declare module 'quagga/src/reader/code_128_reader' {
  declare module.exports: any;
}

declare module 'quagga/src/reader/code_39_reader' {
  declare module.exports: any;
}

declare module 'quagga/src/reader/code_39_vin_reader' {
  declare module.exports: any;
}

declare module 'quagga/src/reader/code_93_reader' {
  declare module.exports: any;
}

declare module 'quagga/src/reader/ean_2_reader' {
  declare module.exports: any;
}

declare module 'quagga/src/reader/ean_5_reader' {
  declare module.exports: any;
}

declare module 'quagga/src/reader/ean_8_reader' {
  declare module.exports: any;
}

declare module 'quagga/src/reader/ean_reader' {
  declare module.exports: any;
}

declare module 'quagga/src/reader/i2of5_reader' {
  declare module.exports: any;
}

declare module 'quagga/src/reader/upc_e_reader' {
  declare module.exports: any;
}

declare module 'quagga/src/reader/upc_reader' {
  declare module.exports: any;
}

declare module 'quagga/tasks/uglyasm' {
  declare module.exports: any;
}

declare module 'quagga/webpack.config' {
  declare module.exports: any;
}

declare module 'quagga/webpack.config.min' {
  declare module.exports: any;
}

declare module 'quagga/webpack.node.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'quagga/dist/quagga.js' {
  declare module.exports: $Exports<'quagga/dist/quagga'>;
}
declare module 'quagga/dist/quagga.min.js' {
  declare module.exports: $Exports<'quagga/dist/quagga.min'>;
}
declare module 'quagga/env/development.js' {
  declare module.exports: $Exports<'quagga/env/development'>;
}
declare module 'quagga/env/node.js' {
  declare module.exports: $Exports<'quagga/env/node'>;
}
declare module 'quagga/env/production.js' {
  declare module.exports: $Exports<'quagga/env/production'>;
}
declare module 'quagga/Gruntfile.js' {
  declare module.exports: $Exports<'quagga/Gruntfile'>;
}
declare module 'quagga/karma-integration.conf.js' {
  declare module.exports: $Exports<'quagga/karma-integration.conf'>;
}
declare module 'quagga/karma.conf.js' {
  declare module.exports: $Exports<'quagga/karma.conf'>;
}
declare module 'quagga/lib/frame_grabber.js' {
  declare module.exports: $Exports<'quagga/lib/frame_grabber'>;
}
declare module 'quagga/lib/input_stream.js' {
  declare module.exports: $Exports<'quagga/lib/input_stream'>;
}
declare module 'quagga/lib/quagga.js' {
  declare module.exports: $Exports<'quagga/lib/quagga'>;
}
declare module 'quagga/plugins/umd.js' {
  declare module.exports: $Exports<'quagga/plugins/umd'>;
}
declare module 'quagga/src/analytics/result_collector.js' {
  declare module.exports: $Exports<'quagga/src/analytics/result_collector'>;
}
declare module 'quagga/src/common/array_helper.js' {
  declare module.exports: $Exports<'quagga/src/common/array_helper'>;
}
declare module 'quagga/src/common/cluster.js' {
  declare module.exports: $Exports<'quagga/src/common/cluster'>;
}
declare module 'quagga/src/common/cv_utils.js' {
  declare module.exports: $Exports<'quagga/src/common/cv_utils'>;
}
declare module 'quagga/src/common/events.js' {
  declare module.exports: $Exports<'quagga/src/common/events'>;
}
declare module 'quagga/src/common/image_debug.js' {
  declare module.exports: $Exports<'quagga/src/common/image_debug'>;
}
declare module 'quagga/src/common/image_wrapper.js' {
  declare module.exports: $Exports<'quagga/src/common/image_wrapper'>;
}
declare module 'quagga/src/common/mediaDevices.js' {
  declare module.exports: $Exports<'quagga/src/common/mediaDevices'>;
}
declare module 'quagga/src/common/subImage.js' {
  declare module.exports: $Exports<'quagga/src/common/subImage'>;
}
declare module 'quagga/src/common/typedefs.js' {
  declare module.exports: $Exports<'quagga/src/common/typedefs'>;
}
declare module 'quagga/src/config/config.dev.js' {
  declare module.exports: $Exports<'quagga/src/config/config.dev'>;
}
declare module 'quagga/src/config/config.js' {
  declare module.exports: $Exports<'quagga/src/config/config'>;
}
declare module 'quagga/src/config/config.node.js' {
  declare module.exports: $Exports<'quagga/src/config/config.node'>;
}
declare module 'quagga/src/config/config.prod.js' {
  declare module.exports: $Exports<'quagga/src/config/config.prod'>;
}
declare module 'quagga/src/decoder/barcode_decoder.js' {
  declare module.exports: $Exports<'quagga/src/decoder/barcode_decoder'>;
}
declare module 'quagga/src/decoder/bresenham.js' {
  declare module.exports: $Exports<'quagga/src/decoder/bresenham'>;
}
declare module 'quagga/src/input/camera_access.js' {
  declare module.exports: $Exports<'quagga/src/input/camera_access'>;
}
declare module 'quagga/src/input/exif_helper.js' {
  declare module.exports: $Exports<'quagga/src/input/exif_helper'>;
}
declare module 'quagga/src/input/frame_grabber.js' {
  declare module.exports: $Exports<'quagga/src/input/frame_grabber'>;
}
declare module 'quagga/src/input/image_loader.js' {
  declare module.exports: $Exports<'quagga/src/input/image_loader'>;
}
declare module 'quagga/src/input/input_stream.js' {
  declare module.exports: $Exports<'quagga/src/input/input_stream'>;
}
declare module 'quagga/src/locator/barcode_locator.js' {
  declare module.exports: $Exports<'quagga/src/locator/barcode_locator'>;
}
declare module 'quagga/src/locator/rasterizer.js' {
  declare module.exports: $Exports<'quagga/src/locator/rasterizer'>;
}
declare module 'quagga/src/locator/skeletonizer.js' {
  declare module.exports: $Exports<'quagga/src/locator/skeletonizer'>;
}
declare module 'quagga/src/locator/tracer.js' {
  declare module.exports: $Exports<'quagga/src/locator/tracer'>;
}
declare module 'quagga/src/quagga.js' {
  declare module.exports: $Exports<'quagga/src/quagga'>;
}
declare module 'quagga/src/reader/2of5_reader.js' {
  declare module.exports: $Exports<'quagga/src/reader/2of5_reader'>;
}
declare module 'quagga/src/reader/barcode_reader.js' {
  declare module.exports: $Exports<'quagga/src/reader/barcode_reader'>;
}
declare module 'quagga/src/reader/codabar_reader.js' {
  declare module.exports: $Exports<'quagga/src/reader/codabar_reader'>;
}
declare module 'quagga/src/reader/code_128_reader.js' {
  declare module.exports: $Exports<'quagga/src/reader/code_128_reader'>;
}
declare module 'quagga/src/reader/code_39_reader.js' {
  declare module.exports: $Exports<'quagga/src/reader/code_39_reader'>;
}
declare module 'quagga/src/reader/code_39_vin_reader.js' {
  declare module.exports: $Exports<'quagga/src/reader/code_39_vin_reader'>;
}
declare module 'quagga/src/reader/code_93_reader.js' {
  declare module.exports: $Exports<'quagga/src/reader/code_93_reader'>;
}
declare module 'quagga/src/reader/ean_2_reader.js' {
  declare module.exports: $Exports<'quagga/src/reader/ean_2_reader'>;
}
declare module 'quagga/src/reader/ean_5_reader.js' {
  declare module.exports: $Exports<'quagga/src/reader/ean_5_reader'>;
}
declare module 'quagga/src/reader/ean_8_reader.js' {
  declare module.exports: $Exports<'quagga/src/reader/ean_8_reader'>;
}
declare module 'quagga/src/reader/ean_reader.js' {
  declare module.exports: $Exports<'quagga/src/reader/ean_reader'>;
}
declare module 'quagga/src/reader/i2of5_reader.js' {
  declare module.exports: $Exports<'quagga/src/reader/i2of5_reader'>;
}
declare module 'quagga/src/reader/upc_e_reader.js' {
  declare module.exports: $Exports<'quagga/src/reader/upc_e_reader'>;
}
declare module 'quagga/src/reader/upc_reader.js' {
  declare module.exports: $Exports<'quagga/src/reader/upc_reader'>;
}
declare module 'quagga/tasks/uglyasm.js' {
  declare module.exports: $Exports<'quagga/tasks/uglyasm'>;
}
declare module 'quagga/webpack.config.js' {
  declare module.exports: $Exports<'quagga/webpack.config'>;
}
declare module 'quagga/webpack.config.min.js' {
  declare module.exports: $Exports<'quagga/webpack.config.min'>;
}
declare module 'quagga/webpack.node.config.js' {
  declare module.exports: $Exports<'quagga/webpack.node.config'>;
}
