// flow-typed signature: 718b35a120edcab9b8f321be7a6887a0
// flow-typed version: <<STUB>>/react-signature-canvas_v^1.0.3/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-signature-canvas'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-signature-canvas' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-signature-canvas/build' {
  declare module.exports: any;
}

declare module 'react-signature-canvas/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-signature-canvas/build/index' {
  declare module.exports: $Exports<'react-signature-canvas/build'>;
}
declare module 'react-signature-canvas/build/index.js' {
  declare module.exports: $Exports<'react-signature-canvas/build'>;
}
declare module 'react-signature-canvas/src/index' {
  declare module.exports: $Exports<'react-signature-canvas/src'>;
}
declare module 'react-signature-canvas/src/index.js' {
  declare module.exports: $Exports<'react-signature-canvas/src'>;
}
