// flow-typed signature: 54cf5403e1712b966f67d12d73134ae7
// flow-typed version: <<STUB>>/signature_pad_v^3.0.0-beta.3/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'signature_pad'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'signature_pad' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'signature_pad/dist/signature_pad' {
  declare module.exports: any;
}

declare module 'signature_pad/dist/signature_pad.m' {
  declare module.exports: any;
}

declare module 'signature_pad/dist/signature_pad.m.min' {
  declare module.exports: any;
}

declare module 'signature_pad/dist/signature_pad.min' {
  declare module.exports: any;
}

declare module 'signature_pad/dist/signature_pad.umd' {
  declare module.exports: any;
}

declare module 'signature_pad/dist/signature_pad.umd.min' {
  declare module.exports: any;
}

declare module 'signature_pad/docs/js/app' {
  declare module.exports: any;
}

declare module 'signature_pad/docs/js/signature_pad.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'signature_pad/dist/signature_pad.js' {
  declare module.exports: $Exports<'signature_pad/dist/signature_pad'>;
}
declare module 'signature_pad/dist/signature_pad.m.js' {
  declare module.exports: $Exports<'signature_pad/dist/signature_pad.m'>;
}
declare module 'signature_pad/dist/signature_pad.m.min.js' {
  declare module.exports: $Exports<'signature_pad/dist/signature_pad.m.min'>;
}
declare module 'signature_pad/dist/signature_pad.min.js' {
  declare module.exports: $Exports<'signature_pad/dist/signature_pad.min'>;
}
declare module 'signature_pad/dist/signature_pad.umd.js' {
  declare module.exports: $Exports<'signature_pad/dist/signature_pad.umd'>;
}
declare module 'signature_pad/dist/signature_pad.umd.min.js' {
  declare module.exports: $Exports<'signature_pad/dist/signature_pad.umd.min'>;
}
declare module 'signature_pad/docs/js/app.js' {
  declare module.exports: $Exports<'signature_pad/docs/js/app'>;
}
declare module 'signature_pad/docs/js/signature_pad.umd.js' {
  declare module.exports: $Exports<'signature_pad/docs/js/signature_pad.umd'>;
}
