// flow-typed signature: d994db7c39dbffc877de3e2835fa35c5
// flow-typed version: <<STUB>>/@blinkmobile/camera_v^0.0.4/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@blinkmobile/camera'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@blinkmobile/camera' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@blinkmobile/camera/dist/bm-camera-cordova' {
  declare module.exports: any;
}

declare module '@blinkmobile/camera/dist/bm-camera-cordova.min' {
  declare module.exports: any;
}

declare module '@blinkmobile/camera/dist/bm-camera-webrtc' {
  declare module.exports: any;
}

declare module '@blinkmobile/camera/dist/bm-camera-webrtc.min' {
  declare module.exports: any;
}

declare module '@blinkmobile/camera/dist/bm-camera' {
  declare module.exports: any;
}

declare module '@blinkmobile/camera/dist/bm-camera.min' {
  declare module.exports: any;
}

declare module '@blinkmobile/camera/example/cordova/www/js/bm-camera-cordova' {
  declare module.exports: any;
}

declare module '@blinkmobile/camera/example/cordova/www/js/bm-camera-cordova.min' {
  declare module.exports: any;
}

declare module '@blinkmobile/camera/example/cordova/www/js' {
  declare module.exports: any;
}

declare module '@blinkmobile/camera/src/camera-factory' {
  declare module.exports: any;
}

declare module '@blinkmobile/camera/src/cordova/camera' {
  declare module.exports: any;
}

declare module '@blinkmobile/camera/src/cordova/cordova-factory' {
  declare module.exports: any;
}

declare module '@blinkmobile/camera/src/webrtc/camera' {
  declare module.exports: any;
}

declare module '@blinkmobile/camera/src/webrtc/webrtc-factory' {
  declare module.exports: any;
}

// Filename aliases
declare module '@blinkmobile/camera/dist/bm-camera-cordova.js' {
  declare module.exports: $Exports<'@blinkmobile/camera/dist/bm-camera-cordova'>;
}
declare module '@blinkmobile/camera/dist/bm-camera-cordova.min.js' {
  declare module.exports: $Exports<'@blinkmobile/camera/dist/bm-camera-cordova.min'>;
}
declare module '@blinkmobile/camera/dist/bm-camera-webrtc.js' {
  declare module.exports: $Exports<'@blinkmobile/camera/dist/bm-camera-webrtc'>;
}
declare module '@blinkmobile/camera/dist/bm-camera-webrtc.min.js' {
  declare module.exports: $Exports<'@blinkmobile/camera/dist/bm-camera-webrtc.min'>;
}
declare module '@blinkmobile/camera/dist/bm-camera.js' {
  declare module.exports: $Exports<'@blinkmobile/camera/dist/bm-camera'>;
}
declare module '@blinkmobile/camera/dist/bm-camera.min.js' {
  declare module.exports: $Exports<'@blinkmobile/camera/dist/bm-camera.min'>;
}
declare module '@blinkmobile/camera/example/cordova/www/js/bm-camera-cordova.js' {
  declare module.exports: $Exports<'@blinkmobile/camera/example/cordova/www/js/bm-camera-cordova'>;
}
declare module '@blinkmobile/camera/example/cordova/www/js/bm-camera-cordova.min.js' {
  declare module.exports: $Exports<'@blinkmobile/camera/example/cordova/www/js/bm-camera-cordova.min'>;
}
declare module '@blinkmobile/camera/example/cordova/www/js/index' {
  declare module.exports: $Exports<'@blinkmobile/camera/example/cordova/www/js'>;
}
declare module '@blinkmobile/camera/example/cordova/www/js/index.js' {
  declare module.exports: $Exports<'@blinkmobile/camera/example/cordova/www/js'>;
}
declare module '@blinkmobile/camera/src/camera-factory.js' {
  declare module.exports: $Exports<'@blinkmobile/camera/src/camera-factory'>;
}
declare module '@blinkmobile/camera/src/cordova/camera.js' {
  declare module.exports: $Exports<'@blinkmobile/camera/src/cordova/camera'>;
}
declare module '@blinkmobile/camera/src/cordova/cordova-factory.js' {
  declare module.exports: $Exports<'@blinkmobile/camera/src/cordova/cordova-factory'>;
}
declare module '@blinkmobile/camera/src/webrtc/camera.js' {
  declare module.exports: $Exports<'@blinkmobile/camera/src/webrtc/camera'>;
}
declare module '@blinkmobile/camera/src/webrtc/webrtc-factory.js' {
  declare module.exports: $Exports<'@blinkmobile/camera/src/webrtc/webrtc-factory'>;
}
