// flow-typed signature: 603263cf8f00e5d983cc91d061a70075
// flow-typed version: <<STUB>>/@blinkmobile/canvas-manipulation_v^1.0.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@blinkmobile/canvas-manipulation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@blinkmobile/canvas-manipulation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@blinkmobile/canvas-manipulation/dist/canvas-manipulation' {
  declare module.exports: any;
}

declare module '@blinkmobile/canvas-manipulation/dist/canvas-manipulation.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@blinkmobile/canvas-manipulation/dist/canvas-manipulation.js' {
  declare module.exports: $Exports<'@blinkmobile/canvas-manipulation/dist/canvas-manipulation'>;
}
declare module '@blinkmobile/canvas-manipulation/dist/canvas-manipulation.min.js' {
  declare module.exports: $Exports<'@blinkmobile/canvas-manipulation/dist/canvas-manipulation.min'>;
}
