// flow-typed signature: 181f1c2530a08bf4ae072994a34c1774
// flow-typed version: <<STUB>>/@blinkmobile/geolocation_v^2.0.3/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@blinkmobile/geolocation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@blinkmobile/geolocation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@blinkmobile/geolocation/geolocation' {
  declare module.exports: any;
}

declare module '@blinkmobile/geolocation/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@blinkmobile/geolocation/geolocation.js' {
  declare module.exports: $Exports<'@blinkmobile/geolocation/geolocation'>;
}
declare module '@blinkmobile/geolocation/types.js' {
  declare module.exports: $Exports<'@blinkmobile/geolocation/types'>;
}
